In [ ]:
import numpy as np

# np.array([array]) -> Cria um array
array = np.array([1, 2, 3])
print(array)


lista = [1, 2, 3], [4, 5, 6]
array = np.array(lista) # Cria um array bidimensional, isso é, com linhas e colunas
print(array)
"""[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]"""

proporcao = array.shape # Retorna a dimensão do array, ou seja, a sua proporção
print(proporcao) # (4, 3) -> 4x3 (4 linhas, 3 colunas)
itens = array.size # Retorna a quantidade de itens que o array apresenta
print(itens) # 12 -> São 12 elementos

In [ ]:
import numpy as np

# np.zeros(numero) -> Cria um array unidimensional preenchido com 0's
array = np.zeros(5) # -> Cria um array com 5 zeros
print(array) # [0. 0. 0. 0. 0.]

# np.zeros((linha, coluna)) -> Cria um array bidimensional preenchido com 0's com proporção
array = np.zeros((3, 2)) # Cria um array 2x3 preenchido por zeros 
print(array)
"""[[0. 0.]
 [0. 0.]
 [0. 0.]]"""


In [ ]:
import numpy as np

# np.ones(numero) -> Cria um array unidimensional preenchido com 1's
array = np.ones(5)
print(array) # [1. 1. 1. 1. 1.]

# np.ones((linha, coluna)) -> Cria um array bidimensional preenchido com 1's com proporção, isso é, linhas e colunas
array = np.ones((6,4))
print(array)
"""[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]"""


In [ ]:
import numpy as np

# np.arange(inicio, fim, passos) -> Gera um array com números que começam desde o número inicial até o número final-1, isso é, se o número final for igual a 15, terminará em 14.
array = np.arange(1, 11) # Gera um array de 1 até 10
print(array) # [ 1  2  3  4  5  6  7  8  9 10]

array = np.arange(0, 11, 2) # Gera um array de 0 até 10 pulando de 2 em 2 números
print(array) # [ 0  2  4  6  8 10]


# np.random.choice(array) -> Escolhe um item aleatório do array
array = np.random.choice([1, 2, 3, 4, 5]) # Escolhe um número aleatório entre 1 a 5
print(array) # 3

# np.random.choice(array, (numero)) -> Escolhe itens aleatórios de um array
array = np.array([0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20])
array = np.random.choice(array, (5)) # Escolhe 5 números aleatórios entre 0 a 20
print(array) # [ 2 10  0 10  6]

array = np.random.choice(array, (3, 2)) # Escolhe 6 números aleatórios, contendo uma proporção de 3x2
print(array)
# """[[18  0]
#  [ 2  0]
#  [18  2]]"""


# np.random.randint(inicio, fim, quantidade) -> Gera números aleatórios entre o número inicial e o número final, com a quantidade indicando a quantidade de números a serem gerados
array = np.random.randint(1, 51, 5) # Gera 5 números de 1 até 51 
print(array) # [ 8 47 11 12 38]

In [ ]:
import numpy as np

# Métodos
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(array) # [ 1  2  3  4  5  6  7  8  9 10]

soma = array.sum()
media = array.mean()
maior = array.max()
menor = array.min()
unicos = np.unique(array)
print(soma, media, maior, menor, unicos)

In [ ]:
import numpy as np

# Indexação e Fatiação
# Acessando elementos de um array unidimensional
# array[item]
array = np.arange(1, 16)
print(array) # [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
print(array[0]) # 1
print(array[4:8]) # [5 6 7 8]

# Acessando elementos de um array bidimensional
# array[linha][coluna]
array = np.array([[1, 2, 3], [4, 5, 6]])
print(array)
"""[[1 2 3]
 [4 5 6]]"""
print(array[0]) # [1 2 3] -> Acessa a primeira coluna
print(array[0][0]) # 1 -> Acessa a primeira coluna e o item no índice 0
print(array[1][2]) # 6 -> Acessa a segunda coluna e o item no índice 2


In [ ]:
import numpy as np

# np.concatenate([array1, array2, ...]) -> Concatena arrays
array1 = np.arange(1, 4)
array2 = np.arange(4, 7)

array = np.concatenate([array1, array2])
print(array) # [1 2 3 4 5 6]

array = np.concatenate([array2, array1])
print(array) # [4 5 6 1 2 3]


In [ ]:
import numpy as np

# np.reshape(linha, coluna) -> Reorganiza um array para um novo formato, desde que a multiplicação entre as dimensões seja igual ao número total de elementos no array. Exemplo: se um array possuir 15 elementos, só pode ser feito um reshape com os valores 3x5, 5x3, 15x1, 1x15, pois o número da coluna multiplicado com o da linha deve dar o resultado do total de elementos. Sendo assim, números primos só podem ter reshape entre 1 e ele mesmo, por exemplo, se o array possuir 7 elementos, então só pode ser feito o reshape com os valores de 1x7 (normal) e 7x1.
array = np.arange(30)

array = array.reshape(2, 15)
print(array)
"""[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]"""

array = np.arange(25).reshape(5, 5)
print(array)
"""[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]"""


In [ ]:
import numpy as np

# array.sort() -> Ordena elementos, axis = 0 ordena na vertical (colunas) e axis = 1 ordena na horizontal (linhas)
array = np.array([[9, 4, 5],
                  [7, 2, 1],
                  [6, 8, 1]])
array.sort(axis=0) # Ordena os itens em coluna
print(array)

array = np.array([[9, 4, 5],
                  [7, 2, 1],
                  [6, 8, 1]])
array.sort(axis=1) # Ordena os itens em linha
print(array)

# array.sort() + np.flipud(array) -> Ordena em ordem decrescente
array = np.array([5, 8, 12, 3, 4, 0, 9])
array.sort()
array = np.flipud(array)
print(array) # [12  9  8  5  4  3  0]


In [ ]:
import numpy as np

# np.split(array, numero) -> Divide um array em pedaços determinados pelo número especificado
array = np.arange(6)

array = np.split(array, 2) # Divide o array em 2 arrays menores
print(array) # [array([0, 1, 2]), array([3, 4, 5])]


In [ ]:
import numpy as np

# np.append([array], ['item']) -> Adiciona um item no final do array
array = np.array([1, 2])

array = np.append(array, [3])
print(array) # [1 2 3]


array = np.append(array, [4, 5])
print(array) # [1 2 3 4 5]


# np.insert([array], posição, ['item']) -> Adiciona um determinado item na posição especificada
array = np.array([1, 3, 4, 5])

array = np.insert([array], 1, [2]) # Adiciona o item 2 no array, na posição 1
print(array) # [1 2 3 4 5]

array = np.insert([array], 5, [6, 7, 8, 9, 10]) # Adiciona os itens 6, 7, 8, 9, 10 no array, na posição 5
print(array) # [ 1  2  3  4  5  6  7  8  9 10]


# np.delete(array, posição(índice)) -> Deleta o item do array na posição especificada
array = np.array([1, 2, 3])
array = np.delete(array, 1) # Deleta o item da posição 1 do array (2)
print(array) # [1 3]

array = np.arange(1, 6)
array = np.delete([array], [0, 1, 2]) # Deleta os itens da posição 0, 1, 2 do array (1, 2, 3)
print(array) # [4 5]


In [ ]:
import numpy as np

# Condições e filtragem
array = np.arange(1, 31)
print(array) # [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]

filtro = array >= 15
print(array[filtro]) # [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]

filtro = array == 50
print(array[filtro]) # []

In [46]:
import numpy as np

# np.full(coluna, numero) -> Preenche apenas colunas com o número especificado
array = np.full(3, 5)
print(array) # [5 5 5]

# np.full((linha, coluna), numero) -> Preenche as linhas e as colunas com o número especificado
array = np.full((2, 4), 7)
print(array)
"""[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]"""

[5 5 5]
[[7 7 7 7]
 [7 7 7 7]]


'[[3 3 3 3]\n [3 3 3 3]\n [3 3 3 3]\n [3 3 3 3]\n [3 3 3 3]]'